repos:
-   repo: local
    hooks:
    -   id: torch-version-check
        name: PyTorch Version Check
        entry: >-
            bash -c 'if grep -r "^[^#]*torch[><=]=\|^[^#]*torch\s*<" . \
            --exclude=".pre-commit-config.yaml" \
            --exclude="requirements.txt" \
            --exclude="constraints.txt" \
            --exclude="cloudbuild.yaml" \
            --exclude="checker.py" \
            --exclude-dir={.git,venv,.venv,site-packages,docker,scripts} \
            --exclude="test.txt" ; then
            echo "Error: Found outdated or dev torch versions"; exit 1; fi'
        language: system
        types: [file]
        exclude: ^\.git/
    -   id: requirements-check
        name: Requirements Version Check
        entry: >-
            bash -c '
            if [ ! -f requirements.txt ]; then
                echo "requirements.txt not found";
                exit 1;
            fi;
            if ! grep -q "^torch==2.0.1" requirements.txt; then
                echo "Error: requirements.txt should use torch==2.0.1";
                exit 1;
            fi'
        language: system
        files: requirements.*\.txt$
    -   id: torch-dev-check
        name: Check for PyTorch Dev Versions
        entry: >-
            bash -c 'if grep -r "torch==.*dev" . --exclude=".pre-commit-config.yaml" --exclude-dir={.git,venv,.venv,site-packages}; then
            echo "Error: Found PyTorch dev versions"; exit 1; fi'
        language: system
        types: [file]
