steps:
# Build the base training image with retries
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
         '-t', 'gcr.io/$PROJECT_ID/scholarai-training:latest',
         '-f', 'docker/training.Dockerfile',
         '--build-arg', 'BUILDKIT_PROGRESS=plain',  # Better logging
         '--no-cache',  # Ensure fresh build
         '--network=host',  # Added for better network stability
         '--memory=4g',     # Added resource limits
         '--cpu-quota=100000',
         '.']
  secretEnv: ['GOOGLE_CREDENTIALS']
  id: 'build-training'
  waitFor: ['-']  # Start immediately
  timeout: '1800s'    # Added timeout
  retryable: true     # Added retry capability

# Build the serving image with retries
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/scholarai-serving:latest', 
         '-f', 'docker/serving.Dockerfile',
         '--build-arg', 'BUILDKIT_PROGRESS=plain',  # Better logging
         '--no-cache',  # Ensure fresh build
         '--network=host',  # Added for better network stability
         '--memory=4g',     # Added resource limits
         '--cpu-quota=100000',
         '.']
  secretEnv: ['GOOGLE_CREDENTIALS']
  id: 'build-serving'
  waitFor: ['-']  # Start immediately
  timeout: '1800s'    # Added timeout
  retryable: true     # Added retry capability

# Push training image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/scholarai-training:latest']

# Push serving image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/scholarai-serving:latest']

# Create Vertex AI model
- name: 'gcr.io/google-cloud-sdk/gcloud'
  args:
  - 'ai'
  - 'models'
  - 'upload'
  - '--region=us-central1' 
  - '--display-name=scholarai-model'
  - '--container-image-uri=gcr.io/${PROJECT_ID}/scholarai-serving:latest'
  - '--container-predict-route=/predict'
  - '--container-health-route=/health'
  secretEnv: ['GOOGLE_CREDENTIALS']

# Set permissions and IAM
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - 'builds'
  - 'triggers'
  - 'create'
  - 'github'
  - '--name=scholarly-trigger'
  - '--repo-owner=${_REPO_OWNER}'
  - '--repo-name=Scholarly'
  - '--branch-pattern=^main$'
  - '--build-config=cloudbuild.yaml'
  - '--region=${_REGION}'
  - '--service-account=projects/${PROJECT_ID}/serviceAccounts/${_SERVICE_ACCOUNT}'
  secretEnv: ['GOOGLE_CREDENTIALS']

timeout: 7200s

substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _REPO_OWNER: ${REPO_OWNER}
  _REGION: us-central1
  _SERVICE_ACCOUNT: scholarly-build-sa@${PROJECT_ID}.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'
  requestedVerifyOption: 'NOT_VERIFIED'
  pool:
    name: 'default'
  dynamic_substitutions: true

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/google-credentials/versions/latest
    env: 'GOOGLE_CREDENTIALS'
