steps:
# Add this step before your Docker builds
- name: 'python:3.10'
  entrypoint: bash
  args:
    - -c
    - |
      python --version
      pip install --upgrade pip
      pip install pip-tools
      pip freeze
      pip install -r requirements.txt --verbose
  id: 'debug-deps'
  timeout: '1800s'

# Add this step before your Docker builds
- name: 'python:3.10'
  entrypoint: bash
  args:
    - -c
    - |
      pip install pip-tools
      pip-compile requirements.txt --upgrade-package "torch>=2.0.1" --allow-unsafe
      pip install -r requirements.txt --no-deps
      pip install -r requirements.txt
  id: 'verify-deps'
  timeout: '1800s'

# Build the base training image with retries (PyTorch 2.5.1)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
         '-t', 'gcr.io/$PROJECT_ID/scholarai-training:latest',
         '-f', 'docker/training.Dockerfile',
         '--build-arg', 'PYTORCH_VERSION=2.0.1',  # Pin specific version
         '--build-arg', 'PYTHON_VERSION=3.10',
         '--network=host',
         '--progress=plain',
         '.']
  secretEnv: ['GOOGLE_CREDENTIALS']
  id: 'build-training'
  waitFor: ['-']  # Start immediately
  timeout: '1800s'    # Added timeout
  retryable: true     # Added retry capability

# Build the serving image with retries (PyTorch 2.5.1)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/scholarai-serving:latest', 
         '-f', 'docker/serving.Dockerfile',
         '--build-arg', 'PYTORCH_VERSION=2.0.1',  # Pin specific version
         '--build-arg', 'PYTHON_VERSION=3.10',
         '--network=host',
         '--progress=plain',
         '.']
  secretEnv: ['GOOGLE_CREDENTIALS']
  id: 'build-serving'
  waitFor: ['-']  # Start immediately
  timeout: '1800s'    # Added timeout
  retryable: true     # Added retry capability

# Push training image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/scholarai-training:latest']

# Push serving image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/scholarai-serving:latest']

# Create Vertex AI model
- name: 'gcr.io/google-cloud-sdk/gcloud'
  args:
  - 'ai'
  - 'models'
  - 'upload'
  - '--region=us-central1' 
  - '--display-name=scholarai-model'
  - '--container-image-uri=gcr.io/${PROJECT_ID}/scholarai-serving:latest'
  - '--container-predict-route=/predict'
  - '--container-health-route=/health'
  secretEnv: ['GOOGLE_CREDENTIALS']

# Set permissions and IAM
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - 'builds'
  - 'triggers'
  - 'create'
  - 'github'
  - '--name=scholarly-trigger'
  - '--repo-owner=${_REPO_OWNER}'
  - '--repo-name=Scholarly'
  - '--branch-pattern=^main$'
  - '--build-config=cloudbuild.yaml'
  - '--region=${_REGION}'
  - '--service-account=projects/${PROJECT_ID}/serviceAccounts/${_SERVICE_ACCOUNT}'
  secretEnv: ['GOOGLE_CREDENTIALS']

timeout: 7200s

substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _REPO_OWNER: ${REPO_OWNER}
  _REGION: us-central1
  _SERVICE_ACCOUNT: scholarly-build-sa@${PROJECT_ID}.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'
  requestedVerifyOption: 'NOT_VERIFIED'
  pool:
    name: 'default'
  dynamic_substitutions: true

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/google-credentials/versions/latest
    env: 'GOOGLE_CREDENTIALS'
