steps:
# Build the base training image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
         '-t', 'gcr.io/$PROJECT_ID/scholarai-training:latest',
         '-f', 'docker/training.Dockerfile',
         '.']
  secretEnv: ['GOOGLE_CREDENTIALS']

# Build the serving image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/$PROJECT_ID/scholarai-serving:latest', 
         '-f', 'docker/serving.Dockerfile',
         '.']
  secretEnv: ['GOOGLE_CREDENTIALS']

# Push training image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/scholarai-training:latest']

# Push serving image  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/scholarai-serving:latest']

# Create Vertex AI model
- name: 'gcr.io/google-cloud-sdk/gcloud'
  args:
  - 'ai'
  - 'models'
  - 'upload'
  - '--region=us-central1' 
  - '--display-name=scholarai-model'
  - '--container-image-uri=gcr.io/${PROJECT_ID}/scholarai-serving:latest'
  - '--container-predict-route=/predict'
  - '--container-health-route=/health'
  secretEnv: ['GOOGLE_CREDENTIALS']

# Set permissions and IAM
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - 'builds'
  - 'triggers'
  - 'create'
  - 'github'
  - '--name=scholarly-trigger'
  - '--repo-owner=${_REPO_OWNER}'
  - '--repo-name=Scholarly'
  - '--branch-pattern=^main$'
  - '--build-config=cloudbuild.yaml'
  - '--region=${_REGION}'
  - '--service-account=projects/${PROJECT_ID}/serviceAccounts/${_SERVICE_ACCOUNT}'

timeout: 3600s

substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _REPO_OWNER: ${REPO_OWNER}
  _REGION: us-central1
  _SERVICE_ACCOUNT: scholarly-build-sa@${PROJECT_ID}.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/google-credentials/versions/latest
    env: 'GOOGLE_CREDENTIALS'
