steps:
# Build training image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/scholarai/scholarai-training:latest',
         '-f', 'docker/training.Dockerfile',
         '--build-arg', 'PYTORCH_VERSION=2.0.1',
         '--build-arg', 'CUDA_VERSION=117',
         '--build-arg', 'PYTHON_VERSION=3.10',
         '--network=host',
         '.']
  id: 'build-training'

# Build serving image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/scholarai/scholarai-serving:latest',
         '-f', 'docker/serving.Dockerfile',
         '--build-arg', 'PYTORCH_VERSION=2.0.1',
         '--build-arg', 'PYTHON_VERSION=3.10',
         '--network=host',
         '.']
  id: 'build-serving'

# Push images
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/scholarai/scholarai-training:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/scholarai/scholarai-serving:latest']

# Get GKE credentials
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['container', 'clusters', 'get-credentials', 'scholarai-cluster', '--zone', 'us-west1-a']

# Deploy to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']

timeout: '3600s'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
