workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-8
    acceleratorType: NVIDIA_TESLA_V100
    acceleratorCount: 2
  replicaCount: 1
  containerSpec:
    imageUri: gcr.io/${PROJECT_ID}/scholarai-training:latest
    args:
      - "--mode=train"
      - "--epochs=10"
      - "--batch_size=128"
      - "--learning_rate=1e-4"
