apiVersion: apps/v1
kind: Deployment
metadata:
  name: scholarai-serving
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scholarai-serving
  template:
    metadata:
      labels:
        app: scholarai-serving
    spec:
      containers:
      - name: serving
        image: us-central1-docker.pkg.dev/${PROJECT_ID}/scholarai/scholarai-serving:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
          requests:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
