apiVersion: v1
kind: ConfigMap
metadata:
  name: training-config
data:
  training_config.yaml: |
    workerPoolSpecs:
      machineSpec:
        machineType: e2-standard-8
        acceleratorType: NVIDIA_TESLA_T4
        acceleratorCount: 1
        zone: us-west1-a
      replicaCount: 1
      containerSpec:
        args:
          - "--mode=train"
          - "--epochs=10"
          - "--batch_size=128"
          - "--learning_rate=1e-4"
